### ISSUE TITLE
The Grid setItemDetails demo is raising errors when embedded inside Vaadin.com

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-grid-flow#191]
URL: https://vaadin.com/components/vaadin-grid/java-examples/using-components
Here is the stacktrace:

```
java.lang.RuntimeException: java.lang.NullPointerException: DataCommunicator can not refresh null object
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:159)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:137)
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.handleNode(PublishedServerEventHandlerRpcHandler.java:116)
	at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:63)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:377)
	at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$0(ServerRpcHandler.java:367)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:367)
	at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:309)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:89)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1495)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:300)
			3 lines skipped for [javax.servlet, org.apache.catalina]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:150)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at com.vaadin.frontend.spring.security.authentication.RequestResponseReferenceFilter.doFilter(RequestResponseReferenceFilter.java:29)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
			5 lines skipped for [org.apache.catalina, org.apache.tomcat]
	at com.vaadin.hummingbird.LoggerFilter.doFilter(LoggerFilter.java:55)
			14 lines skipped for [org.apache.catalina, org.apache.tomcat, org.apache.coyote]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
			1 line skipped for [org.apache.tomcat]
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: DataCommunicator can not refresh null object
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.vaadin.flow.data.provider.DataCommunicator.refresh(DataCommunicator.java:161)
	at com.vaadin.flow.component.grid.Grid$AbstractGridExtension.refresh(Grid.java:696)
	at com.vaadin.flow.component.grid.Grid$DetailsManager.setDetailsVisibleFromClient(Grid.java:824)
	at com.vaadin.flow.component.grid.Grid$DetailsManager.access$800(Grid.java:733)
	at com.vaadin.flow.component.grid.Grid.setDetailsVisible(Grid.java:1926)
			4 lines skipped for [sun., java.lang.reflect.Method]
	at com.vaadin.flow.server.communication.rpc.PublishedServerEventHandlerRpcHandler.invokeMethod(PublishedServerEventHandlerRpcHandler.java:152)
	... 54 more
```

The `DataCommunicator` is refreshed when an item is clicked (to show the details), but in some situations it raises an error on the server.

**Comment by gilberto-torrezan** [comment]
I couldn't reproduce this error when running the demo app, and according to the Vaadin.com team, this error hasn't been seen in the logs for a while. So I'm closing this issue.

**Comment by admlke** [comment]
I have encountered the same mistake as you, how can I solve it?
![image](https://user-images.githubusercontent.com/24238594/49275196-7bea2300-f4b5-11e8-97e7-b9761220bbd2.png)

**Comment by gilberto-torrezan** [comment]
@admlke double check your DataProvider to see if you are not sending any `null` data. Also, make sure you are not calling `DataProvider.refrshItem` or `DataCommunicator.refresh` with `null` in your code.
