### ISSUE TITLE
Filtering a TreeGrid throws a IndexOutOfBoundsException

### ISSUE THREAD

**Issue by abierlerxdev** [vaadin/vaadin-grid-flow#464]
A `IndexOutOfBoundsException` is thrown when you filter a TreeGrid, that contains custom objects.

### How to reproduce
I'm using this class:
```
@Route("")
public class TreeGridDemo extends Div
{
	private final TreeGrid<Project> treegrid = new TreeGrid<>();
	
	public TreeGridDemo()
	{
		//Build a "Main"-Project with 2 "Sub"-Projects
		final Project main = new Project("Main");
		
		final Project sub1 = new Project("Sub1");
		main.getSubprojects().add(sub1);
		sub1.setParent(main);
		
		final Project sub2 = new Project("Sub2");
		main.getSubprojects().add(sub2);
		sub2.setParent(main);
		
		final TreeData<Project> treedata = new TreeData<>();
		
		//Add them to the TreeData
		treedata.addRootItems(main);
		
		treedata.addItem(main, sub1);
		treedata.addItem(main, sub2);
		
		//Set the data into the TreeGrid
		this.treegrid.setTreeData(treedata);
		this.treegrid.addHierarchyColumn(Project::getName);
		
		this.add(this.treegrid);
		
		//Exception here!
		this.add(new Button("Test", l ->
		{
			((TreeDataProvider<Project>)this.treegrid.getDataProvider()).setFilter(Project::getName, t ->
			{
				return t.contains("Sub");
			});
		}));
	}

	public class Project
	{
		private String name = "";

		private List<Project> subprojects = new ArrayList<>();
		private Project parent;
		
		
		public String getName()
		{
			return this.name;
		}

		public void setName(final String name)
		{
			this.name = name;
		}

		public List<Project> getSubprojects()
		{
			return this.subprojects;
		}
		
		public void setSubprojects(final List<Project> subprojects)
		{
			this.subprojects = subprojects;
		}
		
		public Project getParent()
		{
			return this.parent;
		}

		public void setParent(final Project parent)
		{
			this.parent = parent;
		}

		public Project(final String name)
		{
			this.name = name;
		}
	}
}
```

Stack:
```
14:24:17,490 ERROR [com.vaadin.flow.server.DefaultErrorHandler] (default task-26) : java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$getJsonItems$3(DataCommunicator.java:597)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.vaadin.flow.data.provider.DataCommunicator.getJsonItems(DataCommunicator.java:599)
	at com.vaadin.flow.data.provider.DataCommunicator.collectChangesToSend(DataCommunicator.java:547)
	at com.vaadin.flow.data.provider.DataCommunicator.flush(DataCommunicator.java:464)
	at com.vaadin.flow.data.provider.DataCommunicator.lambda$requestFlush$2f364bb9$1(DataCommunicator.java:421)
	at com.vaadin.flow.internal.StateTree.lambda$runExecutionsBeforeClientResponse$1(StateTree.java:350)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.vaadin.flow.internal.StateTree.runExecutionsBeforeClientResponse(StateTree.java:347)
	at com.vaadin.flow.server.communication.UidlWriter.encodeChanges(UidlWriter.java:334)
	at com.vaadin.flow.server.communication.UidlWriter.createUidl(UidlWriter.java:179)
	at com.vaadin.flow.server.communication.UidlRequestHandler.writeUidl(UidlRequestHandler.java:119)
	at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:91)
	at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40)
	at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1533)
	at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:227)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130)
	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:151)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by playa92** [comment]
did you solve it? I have a similar problem with filtering a tree grid

**Comment by silvan-lincan** [comment]
The issue still persists also in Vaadin version 13.0.0.beta1

**Comment by Klaudeta** [comment]
I can identify two issue within here: 
first is the TreeDataProvider's getChildCount method not taking into account the filter set by the setFilter method when a query filter is not present, also not taking into account the query offset and limit:

```
    @Override
    public int getChildCount(
            HierarchicalQuery<T, SerializablePredicate<T>> query) {
        if (query.getFilter().isPresent()) {
            Stream<T> childStream = getFilteredStream(
                    treeData.getChildren(query.getParent()).stream(),
                    query.getFilter());
            return (int) childStream.skip(query.getOffset())
                    .limit(query.getLimit()).count();
        }
        if (query.getParent() != null) {
            return treeData.getChildren(query.getParent()).size();
        } else {
            return treeData.getRootItems().size();
        }
    }
```
Second issue here is the getFilteredStream method itself. The way it is, if the parent (root) of the hierarchy does not pass the filter than they will not be taken into account from the DataCommunicator (HierarchicalDataCommunicator) and so none of the children, even those satisfying the filter will ever be displayed.

The first issue can be fixed by using the getFilteredStream method to filter the children,  and then count them.
While for the second issue I suggest to first flatten the hierarchy of an item with all its children and then check the filter if satisfied for at least one item in the flatten hierarchy.

```
public Stream<T> flatten(T parent) {
        List<T> children = treeData.getChildren(parent);
        return Stream.concat(Stream.of(parent), children.stream().flatMap(o -> flatten(o)));
    }

    private Stream<T> getFilteredStream(Stream<T> stream,
                                        Optional<SerializablePredicate<T>> queryFilter) {
        if (filter != null) {
            stream = stream.filter(parent -> flatten(parent).anyMatch(filter));
        }

        return queryFilter.map(stream::filter).orElse(stream);
    }
```

**Comment by ujoni** [comment]
This should be fixed in Flow `1.4.1` or Vaadin `13.0.0.beta3`.

**Comment by abierlerxdev** [comment]
I think whilst fixing the issue you broke the filtering of the childs...

When I press "Test" nothing get's selected....

**Comment by abierlerxdev** [comment]
And even worse: Trying to use a solution, like this https://github.com/vaadin/framework/issues/9933#issuecomment-466457099 doesn't work also:

```java
@Route("")
public class TreeGridDemoNewSolutionNotWorking extends Div
{
	private final TreeGrid<Project> treegrid = new TreeGrid<>();
	
	public TreeGridDemoNewSolutionNotWorking()
	{
		// Build a "Main"-Project with 2 "Sub"-Projects
		final Project main = new Project("Word_Main");
		
		final Project sub1 = new Project("Word_Sub1");
		main.getSubprojects().add(sub1);
		sub1.setParent(main);
		
		final Project sub2 = new Project("Word_Sub2");
		main.getSubprojects().add(sub2);
		sub2.setParent(main);
		
		// Build a "Main2"-Project with 2 "Sub"-Projects
		final Project main2 = new Project("Word_Main2");
		
		final Project sub21 = new Project("Word_Sub1");
		main.getSubprojects().add(sub21);
		sub21.setParent(main2);
		
		final Project sub22 = new Project("Word_Sub2");
		main.getSubprojects().add(sub22);
		sub22.setParent(main2);
		
		final TreeData<Project> treedata = new TreeData<>();
		
		// Add them to the TreeData
		treedata.addRootItems(main, main2);
		
		treedata.addItem(main, sub1);
		treedata.addItem(main, sub2);
		
		treedata.addItem(main2, sub21);
		treedata.addItem(main2, sub22);
		
		// Set the data into the TreeGrid
		this.treegrid.setTreeData(treedata);
		this.treegrid.addHierarchyColumn(Project::getName);
		
		this.add(this.treegrid);
		
		this.add(new Button("Word", l ->
		{
			((TreeDataProvider<Project>)this.treegrid.getDataProvider()).setFilter(
				detail -> this.matchesFilter(detail, "Word"));
		}));

		this.add(new Button("Sub", l ->
		{
			((TreeDataProvider<Project>)this.treegrid.getDataProvider()).setFilter(
				detail -> this.matchesFilter(detail, "Sub"));
		}));
	}
	
	private boolean matchesFilter(final Project detail, final String filter)
	{
		if(detail.getName().contains(filter))
		{
			System.out.println(detail.getParent() == null ? "root" : detail.getParent().getName() + ">" +detail.getName() + "=" + filter);
			return true;
		}
		return detail.getSubprojects().stream().anyMatch(child -> this.matchesFilter(child, filter));
	}
	
	public class Project
	{
		private String name = "";
		
		private List<Project> subprojects = new ArrayList<>();
		private Project parent;
		
		public String getName()
		{
			return this.name;
		}
		
		public void setName(final String name)
		{
			this.name = name;
		}
		
		public List<Project> getSubprojects()
		{
			return this.subprojects;
		}
		
		public void setSubprojects(final List<Project> subprojects)
		{
			this.subprojects = subprojects;
		}
		
		public Project getParent()
		{
			return this.parent;
		}
		
		public void setParent(final Project parent)
		{
			this.parent = parent;
		}
		
		public Project(final String name)
		{
			this.name = name;
		}
	}
}
```

Causes some desync (with more items in the grid it is even worse)
→ 
![VaadinTreeGridBroken2](https://user-images.githubusercontent.com/45384811/67088026-6d2b5e00-f1a4-11e9-910c-7e9be71e375c.gif)


Seems like the complete TreeGrid filter mechanism is useless now (beside filtering the root-items) :(

**Comment by Klaudeta** [comment]
Hi @abierlerxdev,

The fix done for this issue here did not break the filtering of the children, before the fix the tree grid couldn't be used at all due to IndexOutOfBoundsException when trying to expand any tree node. 
The fix itself makes sure that getChildCount should always return the exact number of children that will be present in the fetchChildren result stream in order to avoid having an IndexOutOfBoundsException from the DataCommunicator. So the change itself is about making sure that getChildCount and fetchChildren are using same exact filtering for the items before returning their results.

In my above comment there is a second issue mentioned that relates to you filter issue you describe , but that was only an observation and no fixes was done for that issue so far.

So good that you opened a new issue for the filtering of children as it really is a new issue.

**Comment by abierlerxdev** [comment]
Hmm ok. 
Thanks for the feed back 😄 
Good thing that I created the new issue
