### ISSUE TITLE
adding datepicker dependecy makes tests fail

### ISSUE THREAD

**Issue by tmattsso** [vaadin/vaadin-grid-flow#468]
when we add this to the POM, tests fail:
```
 <dependency>
           <groupId>com.vaadin</groupId>
           <artifactId>vaadin-date-picker-flow</artifactId>
           <version>1.2-SNAPSHOT</version>
           <scope>test</scope>
           <exclusions>
                <exclusion>
                    <groupId>org.webjars.bowergithub.polymerelements</groupId>
                    <artifactId>iron-flex-layout</artifactId>
                </exclusion>
            </exclusions>
       </dependency>
```

results for `mv verify -PrunTests`

```
Failed tests:   classesSerializable(com.vaadin.flow.component.grid.GridSerializableTest): com.vaadin.flow.component.datepicker.DatePicker
```

```
java.lang.AssertionError: com.vaadin.flow.component.datepicker.DatePicker
	at com.vaadin.flow.testutil.ClassesSerializableTest.serializeAndDeserialize(ClassesSerializableTest.java:384)
	at com.vaadin.flow.testutil.ClassesSerializableTest.classesSerializable(ClassesSerializableTest.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.vaadin.flow.testutil.ClassesSerializableTest.serializeAndDeserialize(ClassesSerializableTest.java:378)
	... 30 more
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.component.datepicker.DatePicker.<init>(DatePicker.java:81)
	at com.vaadin.flow.component.datepicker.DatePicker.<init>(DatePicker.java:67)
	... 35 more
```

**Comment by denis-anisimov** [comment]
The test fails because `DatePicker` CTOR wants `UI` current instance.
That's how `DatePicker`  is implemented.

To be able to prevent the exception you should set a `UI` instance via `UI.setCurrent()`. Same way as it's done here: https://github.com/vaadin/vaadin-date-picker-flow/blob/master/src/test/java/com/vaadin/flow/component/datepicker/DatePickerSerializableTest.java#L21.

But since `DatePicker` is already tested in its own repository you may just exclude it in the `Grid`  repo tests.

This is not a bug in `Grid` repo. This is something you need to be aware of in serializable tests.
