### ISSUE TITLE
Fix TreeGridComponentRendererIT test failure

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-flow#502]
The `TreeGridComponentRendererIT::treegridComponentRenderer_expandCollapseExpand_renderersShows` method fails with : 
```
java.lang.AssertionError: Row with index 3 has no component renderer
	at com.vaadin.flow.component.treegrid.it.TreeGridComponentRendererIT.lambda$assertAllRowsHasTextField$0(TreeGridComponentRendererIT.java:57)
	at com.vaadin.flow.component.treegrid.it.TreeGridComponentRendererIT.assertAllRowsHasTextField(TreeGridComponentRendererIT.java:57)
	at com.vaadin.flow.component.treegrid.it.TreeGridComponentRendererIT.treegridComponentRenderer_expandCollapseExpand_renderersShows(TreeGridComponentRendererIT.java:32)
```

In fact `Dad 0/2` item has no rendered cell in the second column if you look at the screenshot of the failed tests (via artifacts tab).

Locally test passes.
Most likely this is the reason of recent Chrome version upgrade.
It might be the genuine issue in the component's code or just  a test issue.
I've disabled the tests since it prevents validation of any PR.
The reason needs to be investigated and test should be enabled back.

**Comment by ujoni** [comment]
After my Chrome updated to `72.0.3626.96` the test is consistently broken locally. Before the update, the test passed every time, so it it at least somehow Chrome related.

**Comment by pleku** [comment]
Also there is a regression that is related to the broken test so maybe fixing it will fix the failing test too https://github.com/vaadin/flow/issues/5025
