### ISSUE TITLE
Joining columns over multiple headers doesn't work

### ISSUE THREAD

**Issue by mvysny** [vaadin/vaadin-grid-flow#764]
The following unit test reproduces the issue easily:

```java
        grid = new Grid<>();
        firstColumn = grid.addColumn(str -> str).setKey("firstColumn");
        secondColumn = grid.addColumn(str -> str).setKey("secondColumn");
        thirdColumn = grid.addColumn(str -> str).setKey("thirdColumn");
        IconRenderer<String> renderer = new IconRenderer<>(generator -> new Label(":D"));
        fourthColumn = grid.addColumn(renderer).setKey("fourthColumn");
        grid.appendHeaderRow();
        grid.prependHeaderRow().join(firstColumn, secondColumn);
        grid.prependHeaderRow().join(firstColumn, secondColumn, thirdColumn, fourthColumn);
```

Fails with

```
java.lang.IllegalArgumentException: Cannot join cells that are not adjacent

	at com.vaadin.flow.component.grid.AbstractRow.lambda$join$6(AbstractRow.java:274)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:581)
	at com.vaadin.flow.component.grid.AbstractRow.join(AbstractRow.java:272)
	at com.vaadin.flow.component.grid.HeaderRow.join(HeaderRow.java:108)
	at com.vaadin.flow.component.grid.HeaderRow.join(HeaderRow.java:84)
```

**Comment by javier-godoy** [comment]
The following approach also fails:
```
HeaderRow header = grid.prependHeaderRow();
grid.getColumns().forEach(column -> header.getCell(column));
header.join(header.getCells()).setText("Title");
```

In this case the exception is:
```
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653) ~[na:1.8.0_92]
	at java.util.ArrayList.get(ArrayList.java:429) ~[na:1.8.0_92]
	at com.vaadin.flow.component.grid.AbstractRow.joinCellsInPlace(AbstractRow.java:361) ~[vaadin-grid-flow-4.1.5.jar:na]
	at com.vaadin.flow.component.grid.AbstractRow.join(AbstractRow.java:297) ~[vaadin-grid-flow-4.1.5.jar:na]
	at com.vaadin.flow.component.grid.HeaderRow.join(HeaderRow.java:108) ~[vaadin-grid-flow-4.1.5.jar:na]
	at org.vaadin.ext.javier.MainView.<init>(MainView.java:121) ~[classes/:na]
```

Joining all but one column works:
```
header.join(header.getCells().stream().skip(1).collect(Collectors.toList())).setText("Title");
```
