### ISSUE TITLE
Grid fires a selection change event when detached

### ISSUE THREAD

**Issue by Legioth** [vaadin/vaadin-grid-flow#89]
If anything is selected in a Grid when it's being detached, the current selection is being discarded (i.e. losing data) and an event is fired (causing weird behavior e.g. in the case when a selection change in Grid is used to trigger navigation).

The offending stacktrace:
```
	at com.vaadin.flow.component.grid.Grid$SelectionMode$1$1.fireSelectionEvent(Grid.java:162)
	at com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel.doSelect(AbstractGridSingleSelectionModel.java:195)
	at com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel.select(AbstractGridSingleSelectionModel.java:73)
	at com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel.deselect(AbstractGridSingleSelectionModel.java:98)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.vaadin.flow.data.selection.SelectionModel$Single.setSelectedItem(SelectionModel.java:80)
	at com.vaadin.flow.data.selection.SelectionModel$Single.deselectAll(SelectionModel.java:86)
	at com.vaadin.flow.component.grid.AbstractGridSingleSelectionModel.destroyAllData(AbstractGridSingleSelectionModel.java:175)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.vaadin.flow.data.provider.CompositeDataGenerator.destroyAllData(CompositeDataGenerator.java:56)
	at com.vaadin.flow.data.provider.DataCommunicator.handleDetach(DataCommunicator.java:330)
```

**Comment by Legioth** [comment]
Furthermore, this causes a `$0.$connector.doSelection($1,$2)"` RPC be sent for clearing the selection even though `$0` is detached and thus `null`.

**Comment by Legioth** [comment]
To reproduce, navigate to `""`, select one of the items in the grid and then click the link. This navigates to the intended view, but also shows an error notification (`(TypeError) : Cannot read property '$connector' of null`)  in the upper right corner.
```
@Route("")
public class MainView extends Div {
    public MainView() {
        Grid<String> grid = new Grid<>();
        grid.setItems("one", "two");
        grid.addColumn(item -> item);

        add(grid, new RouterLink("Another view", AnotherView.class));
    }
}
```
```
@Route("another")
public class AnotherView extends Div {
    public AnotherView() {
        setText("Another view");
    }
}
```

**Comment by Legioth** [comment]
Another reproduction approach that highlights the lost selection instead of the client-side exception.
Expected that `getSelectedItems()` returns the same value in all three cases, but this isn't the case if any item is selected when clicking the button.

```
Grid<String> grid = new Grid<>();
grid.setItems("one", "two");
grid.addColumn(item -> item);

add(grid, new Button("Detach grid", e -> {
    System.out.println("Before detach: " + grid.getSelectedItems());
    remove(grid);
    System.out.println("After detach: " + grid.getSelectedItems());
    add(grid);
    System.out.println("After reattach: " + grid.getSelectedItems());
}));
```

**Comment by gilberto-torrezan** [comment]
It's more than that. Even without selection, Grid behaves strangely when detached and reattached. This gif shows the behavior of Grid when `setVisible(false)` and when `container.remove(grid)` are called:

![detach_grid](https://user-images.githubusercontent.com/7464735/36599792-263ecf92-18b9-11e8-9ff2-19e58dfc0b96.gif)

With `setVisible(false/true)` everything works as expected, but when detaching and reattaching Grid, all items are lost. On the client-side, `grid._cache.items` is empty. There are no errors on either client or server side consoles.
